# Generated by Django 3.0.5 on 2020-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('comment', models.TextField(max_length=300)),
            ],
        ),
    ]
