# Generated by Django 3.0.5 on 2020-05-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200517_0621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='kategoria',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='kategoria',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Firma',
        ),
        migrations.DeleteModel(
            name='Kategoria',
        ),
    ]
